name: "Build and Push Docker Image"
description: "Builds and pushes a Docker image to GHCR"

inputs:
  service:
    description: "Nx service name"
    required: true
  image:
    description: "Image name on ghcr"
    required: true
  sha:
    description: "Commit SHA"
    required: true
  username:
    description: "GHCR user"
    required: true
  password:
    description: "GHCR password"
    required: true
  node-version:
    description: "Node.js version"
    required: false
    default: "23.x"
  location:
    description: "Path to workspace"
    required: false
    default: ""
  environment:
    description: "Environment to use (run or prod)"
    required: false
    default: "run"
    type: string
  command:
    description: "Optional custom command to execute instead of nx build"
    required: false
    default: ""
  switch-environment:
    description: "Whether to run Prepare environment (swap environments.run.ts)"
    required: false
    type: boolean
    default: true

outputs:
  fullImage:
    value: ${{ steps.meta.outputs.fullImage }}
  commitHash:
    value: ${{ steps.meta.outputs.commitHash }}

runs:
  using: "composite"
  steps:

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Prepare environment
      if: ${{ inputs.switch-environment }}
      shell: bash
      run: |
        pwd
        ls -lah
        rm -f workspace/environments/src/lib/environments.ts
        mv workspace/environments/src/lib/environments.${{ inputs.environment }}.ts workspace/environments/src/lib/environments.ts

    - name: Build Nx service
      if: ${{ inputs.command == '' }}
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        pwd
        ls -lah
        npm ci
        npx nx build ${{ inputs.service }}

    - name: Build service (custom command)
      if: ${{ inputs.command != '' }}
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        pwd
        ls -lah
        npm ci
        ${{ inputs.command }}

    - name: Normalize image owner to lowercase
      id: vars
      shell: bash
      run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

    - name: Prepare image variable
      id: meta
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ inputs.image }}"
        SHORT_SHA="${{ inputs.sha }}"
        SHORT_SHA=${SHORT_SHA:0:7}
        echo "fullImage=$IMAGE" >> $GITHUB_OUTPUT
        echo "commitHash=$SHORT_SHA" >> $GITHUB_OUTPUT

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/${{ inputs.service }}.dockerfile
        push: true
        tags: |
          ${{ steps.meta.outputs.fullImage }}:${{ steps.meta.outputs.commitHash }}
          ${{ steps.meta.outputs.fullImage }}:latest
        build-args: |
          BUILD_TAG=${{ steps.meta.outputs.commitHash }}