name: "Build and Push Docker Image"
description: "Builds and pushes a Docker image to GHCR"

inputs:
  service:
    description: "Nx service name"
    required: true
  image:
    description: "Image name on ghcr"
    required: true
  sha:
    description: "Commit SHA"
    required: true
  username:
    description: "GHCR user"
    required: true
  password:
    description: "GHCR password"
    required: true
  node-version:
    description: "Node.js version"
    required: false
    default: "23.x"
  location:
    description: "Path to workspace"
    required: false
    default: ""

outputs:
  fullImage:
    value: ${{ steps.meta.outputs.fullImage }}
  commitHash:
    value: ${{ steps.meta.outputs.commitHash }}

runs:
  using: "composite"
  steps:

    - name: Debug repo structure 1
      shell: bash
      run: |
        pwd
        ls -lah

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore Nx & npm cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ${{ inputs.location }}workspace/.nx/cache
        key: nx-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          nx-${{ runner.os }}-

    - name: Cache status
      shell: bash
      run: |
        echo "Nx cache hit: ${{ steps.cache.outputs.cache-hit }}"

    - name: Debug repo structure 2
      shell: bash
      run: |
        pwd
        ls -lah
        ls -lah workspace
        ls -lah workspace/.nx

    - name: Build Nx service
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        cd workspace
        npm ci
        npx nx build ${{ inputs.service }}

    - name: Normalize image owner to lowercase
      id: vars
      shell: bash
      run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

    - name: Prepare image variable
      id: meta
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ inputs.image }}"
        SHORT_SHA="${{ inputs.sha }}"
        SHORT_SHA=${SHORT_SHA:0:7}
        echo "fullImage=$IMAGE" >> $GITHUB_OUTPUT
        echo "commitHash=$SHORT_SHA" >> $GITHUB_OUTPUT

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/${{ inputs.service }}.dockerfile
        push: true
        tags: |
          ${{ steps.meta.outputs.fullImage }}:${{ steps.meta.outputs.commitHash }}
          ${{ steps.meta.outputs.fullImage }}:latest
        build-args: |
          BUILD_TAG=${{ steps.meta.outputs.commitHash }}