name: 'NX Build'
description: 'Warm up Nx cache by building all projects'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '23.x'
  command:
    description: 'Nx build command'
    required: false
    default: 'nx run-many --target=build --all --verbose'
  location:
    description: 'Location of the NX Workspace'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Prepare environment
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        rm -f workspace/environments/src/lib/environments.ts
        mv workspace/environments/src/lib/environments.run.ts workspace/environments/src/lib/environments.ts

    - name: Restore Nx & npm cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ${{ inputs.location }}workspace/.nx/cache
        key: nx-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          nx-${{ runner.os }}-

    - name: Install dependencies & Build all Nx projects
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        cd workspace
        npm ci
        npx nx --version
        ${{ inputs.command }}

    - name: Debug repo structure
      shell: bash
      run: |
        pwd
        ls -lah
        ls -lah workspace
        ls -lah workspace/.nx
