name: "Deploy to Kubernetes"
description: "Applies Kubernetes manifests for a given service using a kubeconfig secret."

inputs:
  kubeconfig:
    description: "Base64 encoded kubeconfig"
    required: true
  service:
    description: "Service name (e.g., backend)"
    required: true
  image:
    description: "Full image reference (e.g., ghcr.io/org/app:sha-...)"
    required: true
  commitHash:
    description: "Commit Hash for the deployment Tag"
    required: true
  namespace:
    description: "Kubernetes namespace"
    required: false
    default: "wudio"

runs:
  using: "composite"
  steps:

    # 1️⃣ Write kubeconfig
    - name: Set up kubeconfig
      shell: bash
      run: |
        echo "${{ inputs.kubeconfig }}" > kubeconfig.yaml
        mkdir -p ~/.kube
        cp kubeconfig.yaml ~/.kube/config
        chmod 600 ~/.kube/config
        echo "✅ Kubeconfig setup complete"
    
    # 2️⃣ Verify cluster connection
    - name: Verify connection
      shell: bash
      run: kubectl get nodes

    - name: Create namespace if not exists
      shell: bash
      run: |
        if kubectl get namespace ${{ inputs.namespace }} >/dev/null 2>&1; then
          echo "✅ Namespace '${{ inputs.namespace }}' already exists."
        else
          echo "🚀 Creating namespace '${{ inputs.namespace }}'..."
          kubectl create namespace ${{ inputs.namespace }}
        fi


    # 3️⃣ Apply deployment + service
    - name: Apply manifests
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.commitHash }}
        K8S_NAMESPACE: ${{ inputs.namespace }}
      run: |

        # Prüfe, ob image leer ist
        if [ -z "${{ inputs.image }}" ]; then
          echo "❌ ERROR: inputs.image ist leer!"
        else
          echo "✔ inputs.image ist gesetzt"
        fi

        # Prüfe IMAGE_TAG
        if [ -z "${IMAGE_TAG}" ]; then
          echo "❌ ERROR: IMAGE_TAG ist leer!"
        else
          echo "✔ IMAGE_TAG ist gesetzt"
        fi

        # Jetzt final zusammensetzen
        IMAGE="${{ inputs.image }}:${IMAGE_TAG}"
        echo "🔄 Deploying service ${{ inputs.service }} with image $IMAGE"

        if ! kubectl set image deployment/${{ inputs.service }} \
          ${{ inputs.service }}=$IMAGE -n ${{ inputs.namespace }}; then
          echo "ℹ️ Deployment not found, creating new one..."
          envsubst < deployments/deployment.${{ inputs.service }}.yml | \
            kubectl apply -f - -n ${{ inputs.namespace }}
        fi