name: "Build and Push Docker Image"
description: "Builds and pushes a Docker image to GHCR, including all preparation steps."

inputs:
  service:
    description: "The service name (e.g., backend, dashboard)"
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '23.x'
  command:
    description: 'Nx build command to run (default: build all)'
    required: false
    default: 'nx run-many --target=build --all --verbose'
  image:
    description: "Image name on ghcr (e.g. wudio-backend, wudio-dashboard, wudio-actions)"
    required: true
  sha:
    description: "Commit SHA for tagging"
    required: true
  username:
    description: "GHCR user"
    required: true
  password:
    description: "GHCR password"
    required: true
  location:
    description: 'Location of the NX Workspace'
    required: false
    default: ''



outputs:
  fullImage:
    description: "Full image name with tag (e.g. 4c6c436c)"
    value: ${{ steps.meta.outputs.fullImage }}
  commitHash:
    description: "Commit Hash which is used as tag (e.g. ghcr.io/org/wudio-backend)"
    value: ${{ steps.meta.outputs.commitHash }}

runs:
  using: "composite"
  steps:
    # 1️⃣ Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v5

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Prepare environment
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        rm -f workspace/environments/src/lib/environments.ts
        mv workspace/environments/src/lib/environments.run.ts workspace/environments/src/lib/environments.ts

    - name: Install dependencies & Build all Nx projects
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        cd workspace
        npm install -g nx
        npm ci
        ${{ inputs.command }}

    # 2️⃣ Normalize image owner to lowercase
    - name: Normalize image owner to lowercase
      id: vars
      shell: bash
      run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

    - name: Prepare image variable
      id: meta
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ inputs.image }}"
        SHORT_SHA="${{ inputs.sha }}"
        SHORT_SHA=${SHORT_SHA:0:7}
        echo "fullImage=$IMAGE" >> $GITHUB_OUTPUT
        echo "commitHash=$SHORT_SHA" >> $GITHUB_OUTPUT

    # 4️⃣ Login to GHCR
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Debug Print Docker build context (dry run)
      shell: bash
      run: |
        docker build \
          --no-cache \
          --progress=plain \
          --file docker/${{ inputs.service }}.dockerfile \
          --build-arg BUILD_TAG=${{ steps.meta.outputs.commitHash }} \
          .

    # 5️⃣ Build & Push the service
    - name: Build & Push ${{ inputs.service }}
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/${{ inputs.service }}.dockerfile
        push: true
        tags: |
          ${{ steps.meta.outputs.fullImage }}:${{ steps.meta.outputs.commitHash }}
          ${{ steps.meta.outputs.fullImage }}:latest
        build-args: |
          BUILD_TAG=${{ steps.meta.outputs.commitHash }}
